version: 0.0
os: linux
files:
  - source: Code
    destination: /home/ubuntu/Code
  - source: Assets
    destination: /home/ubuntu/Assets 
hooks:
  BeforeInstall:
    - location: Assets/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: Assets/scripts/install_app.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: Assets/scripts/stop_server.sh
      timeout: 300
      runas: root
